graph TD
%% 外力计算
subgraph  wl[外力计算]
start("输入挡墙、填土数据")
report(保存结果)
start -->|土压力|t1
t1("遍历第一、二破裂角")-.->
t2(计算填土重力) -.->
t3(计算土压力E) -.-> t1
t1 -->|遍历结束| t4(保存E的最大值作为主动土压力) -->
t5(保存破裂角度) -->
t6(绘制土压力应力图) -->
t7(计算应力图形心的y坐标) -->
t8(将y代入墙背方程得到土压力作用点位置)-->report

start -->|重力|z1
z1("计算第二破裂面间土体与挡墙截面积、重心") -->
z2(计算墙身重力大小) -->
a3(计算重心位置) --> report

start -->|地震力|p1
p1("计算第二破裂面到实际墙背间的填土截面积") -->
p2(计算地震力大小) -->
p3(计算作用点位置)  --> report
end


%% 稳定性检算
subgraph wd[稳定性检算]
start1("输入分项系数、外力")-->|抗滑动|kc1
kc1(计算不同组合的不平衡作用设计值) -->
kc2(计算不同组合的平衡作用设计值) -->
kc3(取最不利情况作为结果)-->result
start1 --> |抗倾覆|k01
k01(计算不同组合的不平衡作用设计值) -->
k02(计算不同组合的平衡作用设计值) -->
k03(取最不利情况作为结果)-->result

start1 --> |偏心距及承载力|e1
e1(计算稳定力系力矩) -->
e2(计算倾覆力系力矩) -->
e3(计算偏心距) -->
e4(验证偏心距限定值) -->
d1(按不同偏心距计算地基应力) -->
d2(计算正常使用极限状态作用组合效应的设计值) -->
d3(计算路基结构正常使用状态限值) -->
d4(取不同组合下最不利情况) -->
result(输出报告)
end
